services:
  db:
    container_name: db
    image: mysql
    restart: always
    networks: 
      - budget-vlan
    volumes:
      - /home/chromium/budget/etc-conf.d:/etc/mysql/conf.d
      - /var/lib/budget/db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "budget"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
  backend:
    container_name: backend
    image: windingtherope/budget-backend
    networks: 
      - budget-vlan
    restart: always
    environment:
      DB: "budget"
      DBUSER: "user"
      DBPASS: "password"
      DBADDR: "db:3306"
      GIN_MODE: debug
      WEBIP: backend
    depends_on:
      - db
  frontend:
    container_name: frontend
    image: windingtherope/budget-frontend
    networks:
      - budget-vlan
    restart: always
    depends_on:
      - backend
  budget-proxy:
    image: nginx
    restart: always
    networks:
      - budget-vlan
    ports:
      - "8080:80"
    volumes:
      - ./etc-nginx-conf.d:/etc/nginx/conf.d/
    depends_on:
      - frontend
      - backend
networks:
  budget-vlan:
    driver: bridge
